### ISSUE TITLE
Error whenever I run index.py. I used correct bot token

### ISSUE THREAD

**Issue by KC080** [Eddy-Arch/Hentai-discord-bot#10]
![image](https://user-images.githubusercontent.com/77486627/118800404-70cc1d00-b8d2-11eb-9f4d-262bbe23912f.png)

**Comment by Eddy-Arch** [comment]
try reinstalling discord.py, regenerating the token, and making sure to start index.py with python3

**Comment by Eddy-Arch** [comment]
im assuming its fixed.
