### ISSUE TITLE
no module named nekos

### ISSUE THREAD

**Issue by localht** [Eddy-Arch/Hentai-discord-bot#19]
when i run the bot the following error comes up

$ pip install nekos
Requirement already satisfied: nekos in /data/data/com.termux/files/usr/lib/python3.11/site-packages (0.1)
.../0/hentai-discord-bot $ python index.py
Traceback (most recent call last):
  File "/storage/emulated/0/Hentai-discord-bot/index.py", line 3, in <module>
    import time, requests, nekos, sys, os, config
ModuleNotFoundError: No module named 'nekos'
.../0/hentai-discord-bot $

**Comment by localht** [comment]
bro i'm terribly sorry for making an issue for an error that i could've easily fix,
i got the error fixed by just installing nekos by requirements.txt

**Comment by Eddy-Arch** [comment]
All good, the reason this didn’t work is because nekos.py isn’t available in pip’s repos, or at least the version they have out now is incompatible with the bot. In requirements.txt i specified the package for this exact reason
