### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by Eddy-Arch** [Eddy-Arch/Hentai-discord-bot#2]
we need to add a ticketing system and warning based kicks.
we also need to fix the muting

**Comment by weedoe** [comment]
muting as in?

**Comment by Eddy-Arch** [comment]
> muting as in?
heres what i was thinking:
given no time argument, just mute (as in, give the user the muted role)
given a time argument, (either (x)m or (x)h) mute the user and wait the X amount of hours/mins 
to unmute

**Comment by Eddy-Arch** [comment]
i have added the feature a long time ago
